### ISSUE TITLE
Border Issue 

### ISSUE THREAD

**Issue by noomerzx** [Sellsuki/begeta#43]
ตอนนี้ borde-style มันกำหนด top, bottom, left, right ไม่ได้เลยทำสไตล์แบบ border-bottom:1px solid black ไม่ได้เพราะลองใส่ "bd-st-solid bd-cl-light bd-bt-w-1px" แล้วขอบซ้ายขวา มันจะกลายเปน margin เพราะเรากำหนดสไตล์แบบครอบคลุมหมด

**Comment by TonPC64** [comment]
ถ้าจะ border bottom only ต้องเซ็ต bd-w-0px ก่อนอ่ะครับ
