### ISSUE TITLE
Flex grow class missing

### ISSUE THREAD

**Issue by noomerzx** [Sellsuki/begeta#44]
ไม่มี class ให้ใช้สำหรับ flex grow งะ

**Comment by TonPC64** [comment]
วิธีใช้จะเป็นยังไงอ่ะครับ ประมาณ f-g-1 หรือป่าว แต่ต้องการให้มีค่าเท่าไหร่บ้าง
ช่วยแนะที หรือพี่ contribute เลยก็ได้นะ

**Comment by noomerzx** [comment]
ปกติ flex เฉยๆมันจะรับ 3 ค่า
flex: <'flex-grow'> <'flex-shrink'> <'flex-basis'> 

example = flex: 1 1 200px;

ใน begeta ใส่แต่ตัวแรก flex: 1 น่าจะหมายความว่ามันคือ flex-grow อย่างเดียวนะ

ลองดูเป็น optional ละกันว่าจะแยกหรือยังไงดี

https://css-tricks.com/almanac/properties/f/flex/

**Comment by TonPC64** [comment]
#51 น่าจะครบละ
