### ISSUE TITLE
Box Size Docs and Classes improvement

### ISSUE THREAD

**Issue by noomerzx** [Sellsuki/begeta#46]
ตอนแรกหา width height ไม่เจองะ ไม่รู้ว่า Box Size คืออะไรไม่รู้โง่เอง หรือลองถามคนอื่นดูว่าเป็นกันเปล่า พี่งงแสสเขียน  custom ไปเต็มเลย

ส่วน improvement อยากได้ครบเลย
min-width
min-height
max-width
max-height

เหมือนมันจะยังมีไม่ครบ

เพิ่มเติมตรง width value น่าจะเพิ่มไปอีก อันนี้ลองปรึกษาคนอื่นดู เพราะปกติใช้ dp-flex แล้วจะ fixed width ด้านนึงแล้วให้อีกด้านมัน auto เลยซึ่ง value width 100px มันน้อยไป ซัก 300 น่าจะกำลังดี

**Comment by TonPC64** [comment]
มีหมดละครับ แต่ลืมเขียน docs

**Comment by TonPC64** [comment]
mn-w คือ min-width
mn-w คือ max-width

**Comment by TonPC64** [comment]
แก้แล้วครับ
