### ISSUE TITLE
เปลี่ยน Logo

### ISSUE THREAD

**Issue by n9ti** [Sellsuki/begeta#49]
เปลี่ยนจากรูปนี้
![old](https://camo.githubusercontent.com/36c914f85cddf3817c5b124197cc9d5265f396a8/68747470733a2f2f64333079396364737537786c67302e636c6f756466726f6e742e6e65742f706e672f35383034332d3230302e706e67)
ไปเป็นรูปนี้
![new](https://begeta.netlify.com/images/logo-atomic.svg)

**Comment by TonPC64** [comment]
แก้แล้วครับ #53
